name: iterlife-idaas

services:
  iterlife-idaas-api:
    image: ${RUNTIME_API_IMAGE_NAME:-iterlife-idaas-api:prod}
    container_name: iterlife-idaas-api
    env_file:
      - ${BACKEND_ENV_FILE:-/apps/config/iterlife-idaas/backend.env}
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      JAVA_TOOL_OPTIONS: -Duser.timezone=${TZ:-Asia/Shanghai} -Djdk.http.auth.tunneling.disabledSchemes=
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${API_BIND_HOST:-127.0.0.1}:${API_PORT:-18280}:8088"
